// This file was autogenerated by print_selective_registration_header.py

constexpr int strcmpc(const char* a, const char* b)
{
  return *a == 0 && *b == 0 ? 0 :
  *a == ' ' ? strcmpc(a+1,b) :
  *b == ' ' ? strcmpc(a,b+1) :
  *a == 0 ? -1 :
  *b == 0 ? 1 :
  *a < *b ? -1 :
  *a > *b ? 1 :
  *a == *b ? strcmpc(a+1, b+1) :
  false;
}

#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER
constexpr inline bool ShouldRegisterOp(const char op[]) {
  return false
     || (strcmpc(op, "Add") == 0)
     || (strcmpc(op, "All") == 0)
     || (strcmpc(op, "ArgMax") == 0)
     || (strcmpc(op, "Assert") == 0)
     || (strcmpc(op, "BiasAdd") == 0)
     || (strcmpc(op, "Cast") == 0)
     || (strcmpc(op, "ConcatV2") == 0)
     || (strcmpc(op, "Const") == 0)
     || (strcmpc(op, "Enter") == 0)
     || (strcmpc(op, "Equal") == 0)
     || (strcmpc(op, "Exit") == 0)
     || (strcmpc(op, "Fill") == 0)
     || (strcmpc(op, "Gather") == 0)
     || (strcmpc(op, "GreaterEqual") == 0)
     || (strcmpc(op, "Identity") == 0)
     || (strcmpc(op, "Less") == 0)
     || (strcmpc(op, "LessEqual") == 0)
     || (strcmpc(op, "LogicalNot") == 0)
     || (strcmpc(op, "LogicalOr") == 0)
     || (strcmpc(op, "LoopCond") == 0)
     || (strcmpc(op, "MatMul") == 0)
     || (strcmpc(op, "Merge") == 0)
     || (strcmpc(op, "Mul") == 0)
     || (strcmpc(op, "NextIteration") == 0)
     || (strcmpc(op, "NoOp") == 0)
     || (strcmpc(op, "Pack") == 0)
     || (strcmpc(op, "Placeholder") == 0)
     || (strcmpc(op, "Range") == 0)
     || (strcmpc(op, "Select") == 0)
     || (strcmpc(op, "Shape") == 0)
     || (strcmpc(op, "Sigmoid") == 0)
     || (strcmpc(op, "Size") == 0)
     || (strcmpc(op, "Split") == 0)
     || (strcmpc(op, "StridedSlice") == 0)
     || (strcmpc(op, "Switch") == 0)
     || (strcmpc(op, "Tanh") == 0)
     || (strcmpc(op, "TensorArrayGatherV3") == 0)
     || (strcmpc(op, "TensorArrayReadV3") == 0)
     || (strcmpc(op, "TensorArrayScatterV3") == 0)
     || (strcmpc(op, "TensorArraySizeV3") == 0)
     || (strcmpc(op, "TensorArrayV3") == 0)
     || (strcmpc(op, "TensorArrayWriteV3") == 0)
     || (strcmpc(op, "Tile") == 0)
     || (strcmpc(op, "Transpose") == 0)
     || (strcmpc(op, "_Recv") == 0)
     || (strcmpc(op, "_Send") == 0)
  ;
}
#define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)


    namespace {
      constexpr const char* skip(const char* x) {
        return (*x) ? (*x == ' ' ? skip(x + 1) : x) : x;
      }

      constexpr bool isequal(const char* x, const char* y) {
        return (*skip(x) && *skip(y))
                   ? (*skip(x) == *skip(y) && isequal(skip(x) + 1, skip(y) + 1))
                   : (!*skip(x) && !*skip(y));
      }

      template<int N>
      struct find_in {
        static constexpr bool f(const char* x, const char* const y[N]) {
          return isequal(x, y[0]) || find_in<N - 1>::f(x, y + 1);
        }
      };

      template<>
      struct find_in<0> {
        static constexpr bool f(const char* x, const char* const y[]) {
          return false;
        }
      };
    }  // end namespace
    constexpr const char* kNecessaryOpKernelClasses[] = {
"BinaryOp< CPUDevice, functor::add<float>>",
"BinaryOp< CPUDevice, functor::add<int32>>",
"ReductionOp<CPUDevice, bool, Eigen::internal::AndReducer>",
"ArgMaxOp<CPUDevice, float>",
"AssertOp",
"BiasOp<CPUDevice, float>",
"CpuCastOp",
"ConcatV2Op<CPUDevice, ::tensorflow::int32>",
"ConcatV2Op<CPUDevice, float>",
"ConstantOp",
"EnterOp",
"BinaryOp< CPUDevice, functor::equal_to<int32>>",
"ExitOp",
"FillOp<CPUDevice, float>",
"GatherOp<CPUDevice, float, int32>",
"BinaryOp< CPUDevice, functor::greater_equal<int32>>",
"IdentityOp",
"BinaryOp< CPUDevice, functor::less<int32>>",
"BinaryOp< CPUDevice, functor::less_equal<int32>>",
"UnaryOp<CPUDevice, functor::logical_not>",
"BinaryOp<CPUDevice, functor::logical_or>",
"LoopCondOp",
"MatMulOp<CPUDevice, float, false >",
"MergeOp",
"BinaryOp< CPUDevice, functor::mul<float>>",
"NextIterationOp",
"NoOp",
"PackOp<CPUDevice, ::tensorflow::int32>",
"PlaceholderOp",
"RangeOp<::tensorflow::int32>",
"SelectOp<CPUDevice, float>",
"ShapeOp<int32>",
"UnaryOp< CPUDevice, functor::sigmoid<float>>",
"SizeOp<int32>",
"SplitOpCPU<float>",
"StridedSliceOp<CPUDevice, ::tensorflow::int32>",
"SwitchOp",
"UnaryOp< CPUDevice, functor::tanh<float>>",
"TensorArrayPackOrGatherOp<CPUDevice, float, false >",
"TensorArrayReadOp<CPUDevice, float>",
"TensorArrayUnpackOrScatterOp<CPUDevice, float, false >",
"TensorArraySizeOp",
"TensorArrayOp",
"TensorArrayWriteOp<CPUDevice, float>",
"TileOp<CPUDevice>",
"TransposeCpuOp",
"RecvOp",
"SendOp",
};
#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

#define SHOULD_REGISTER_OP_GRADIENT false
#endif
